print("How old are you?")
age = input()
age=int(age)
print("How tall are you?") 
height =input()
height=str(height)
print("How much do you weigh?")
weight = input()
weight=int(weight)
print("So, you're %r old, %r tall and %r heavy." % (
age, height, weight)) 